[2022-06-28 15:33:16,779] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_to_dw_bq.bq_external_table_task manual__2022-06-28T15:33:11.400175+00:00 [queued]>
[2022-06-28 15:33:16,788] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_to_dw_bq.bq_external_table_task manual__2022-06-28T15:33:11.400175+00:00 [queued]>
[2022-06-28 15:33:16,788] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 15:33:16,788] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-28 15:33:16,789] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 15:33:16,804] {taskinstance.py:1377} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bq_external_table_task> on 2022-06-28 15:33:11.400175+00:00
[2022-06-28 15:33:16,810] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-28 15:33:16,810] {standard_task_runner.py:52} INFO - Started process 1416 to run task
[2022-06-28 15:33:16,813] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_to_dw_bq', 'bq_external_table_task', 'manual__2022-06-28T15:33:11.400175+00:00', '--job-id', '548', '--raw', '--subdir', 'DAGS_FOLDER/03_data to_dw_dag.py', '--cfg-path', '/tmp/tmprvecaj22', '--error-file', '/tmp/tmpymr8gp63']
[2022-06-28 15:33:16,814] {standard_task_runner.py:80} INFO - Job 548: Subtask bq_external_table_task
[2022-06-28 15:33:16,857] {task_command.py:370} INFO - Running <TaskInstance: data_to_dw_bq.bq_external_table_task manual__2022-06-28T15:33:11.400175+00:00 [running]> on host 7c6db1b27447
[2022-06-28 15:33:16,925] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_to_dw_bq
AIRFLOW_CTX_TASK_ID=bq_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-28T15:33:11.400175+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-28T15:33:11.400175+00:00
[2022-06-28 15:33:16,926] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-06-28 15:33:16,926] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-06-28 15:33:17,566] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-06-28 15:33:17,567] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-28 15:33:17,567] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 507, in send_command
    "Error while sending", e, proto.ERROR_ON_SEND)
py4j.protocol.Py4JNetworkError: Error while sending
[2022-06-28 15:33:17,569] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-28 15:33:17,573] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_to_dw_bq, task_id=bq_external_table_task, execution_date=20220628T153311, start_date=20220628T153316, end_date=20220628T153317
[2022-06-28 15:33:17,626] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-28 15:33:17,668] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
