[2022-06-21 18:00:44,834] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.rm_task manual__2022-06-21T18:00:43.293944+00:00 [queued]>
[2022-06-21 18:00:44,840] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.rm_task manual__2022-06-21T18:00:43.293944+00:00 [queued]>
[2022-06-21 18:00:44,840] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 18:00:44,840] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-21 18:00:44,840] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 18:00:44,851] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): rm_task> on 2022-06-21 18:00:43.293944+00:00
[2022-06-21 18:00:44,857] {standard_task_runner.py:52} INFO - Started process 208 to run task
[2022-06-21 18:00:44,860] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'rm_task', 'manual__2022-06-21T18:00:43.293944+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmppdk3r3x9', '--error-file', '/tmp/tmpgwbnkqdo']
[2022-06-21 18:00:44,860] {standard_task_runner.py:80} INFO - Job 88: Subtask rm_task
[2022-06-21 18:00:44,919] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_gcs_dag.rm_task manual__2022-06-21T18:00:43.293944+00:00 [running]> on host 5a0eab06deba
[2022-06-21 18:00:44,981] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=rm_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T18:00:43.293944+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-21T18:00:43.293944+00:00
[2022-06-21 18:00:44,982] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-21 18:00:44,982] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm brooklyn.csv brooklyn-food-waste.zip']
[2022-06-21 18:00:44,995] {subprocess.py:85} INFO - Output:
[2022-06-21 18:00:44,997] {subprocess.py:92} INFO - rm: cannot remove 'brooklyn.csv': No such file or directory
[2022-06-21 18:00:44,997] {subprocess.py:92} INFO - rm: cannot remove 'brooklyn-food-waste.zip': No such file or directory
[2022-06-21 18:00:44,998] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-21 18:00:45,008] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-21 18:00:45,010] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=rm_task, execution_date=20220621T180043, start_date=20220621T180044, end_date=20220621T180045
[2022-06-21 18:00:45,020] {standard_task_runner.py:97} ERROR - Failed to execute job 88 for task rm_task (Bash command failed. The command returned a non-zero exit code 1.; 208)
[2022-06-21 18:00:45,032] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-21 18:00:45,061] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
