[2022-06-21 15:34:42,603] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-06-21T15:29:37.286778+00:00 [queued]>
[2022-06-21 15:34:42,631] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-06-21T15:29:37.286778+00:00 [queued]>
[2022-06-21 15:34:42,631] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 15:34:42,631] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-06-21 15:34:42,631] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 15:34:42,674] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2022-06-21 15:29:37.286778+00:00
[2022-06-21 15:34:42,686] {standard_task_runner.py:52} INFO - Started process 365 to run task
[2022-06-21 15:34:42,692] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2022-06-21T15:29:37.286778+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp9m9ajhah', '--error-file', '/tmp/tmptiagblsi']
[2022-06-21 15:34:42,699] {standard_task_runner.py:80} INFO - Job 12: Subtask download_dataset_task
[2022-06-21 15:34:42,801] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-06-21T15:29:37.286778+00:00 [running]> on host 4540fdd3d75e
[2022-06-21 15:34:43,003] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T15:29:37.286778+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-21T15:29:37.286778+00:00
[2022-06-21 15:34:43,053] {logging_mixin.py:115} INFO - Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
[2022-06-21 15:34:43,056] {logging_mixin.py:115} INFO - Your Kaggle username:
[2022-06-21 15:34:43,056] {logging_mixin.py:115} INFO -  
[2022-06-21 15:34:43,057] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags.py", line 26, in download_data
    op.download(dataset_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/opendatasets/__init__.py", line 13, in download
    return download_kaggle_dataset(dataset_id_or_url, data_dir=data_dir, force=force, dry_run=dry_run)
  File "/home/airflow/.local/lib/python3.7/site-packages/opendatasets/utils/kaggle_api.py", line 46, in download_kaggle_dataset
    os.environ['KAGGLE_USERNAME'] = click.prompt("Your Kaggle username")
  File "/home/airflow/.local/lib/python3.7/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/home/airflow/.local/lib/python3.7/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort
[2022-06-21 15:34:43,075] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20220621T152937, start_date=20220621T153442, end_date=20220621T153443
[2022-06-21 15:34:43,102] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task download_dataset_task (; 365)
[2022-06-21 15:34:43,149] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-21 15:34:43,268] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
