[2022-06-27 13:19:10,539] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process-food-waste-data.process_data_task manual__2022-06-27T13:19:05.540674+00:00 [queued]>
[2022-06-27 13:19:10,546] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process-food-waste-data.process_data_task manual__2022-06-27T13:19:05.540674+00:00 [queued]>
[2022-06-27 13:19:10,546] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:19:10,546] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-27 13:19:10,546] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:19:10,558] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): process_data_task> on 2022-06-27 13:19:05.540674+00:00
[2022-06-27 13:19:10,563] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-27 13:19:10,563] {standard_task_runner.py:52} INFO - Started process 535 to run task
[2022-06-27 13:19:10,566] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process-food-waste-data', 'process_data_task', 'manual__2022-06-27T13:19:05.540674+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/02_data_process_dag.py', '--cfg-path', '/tmp/tmpxpm1513i', '--error-file', '/tmp/tmpzlquefa8']
[2022-06-27 13:19:10,567] {standard_task_runner.py:80} INFO - Job 384: Subtask process_data_task
[2022-06-27 13:19:10,604] {task_command.py:370} INFO - Running <TaskInstance: process-food-waste-data.process_data_task manual__2022-06-27T13:19:05.540674+00:00 [running]> on host c8b7aec393e9
[2022-06-27 13:19:10,662] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process-food-waste-data
AIRFLOW_CTX_TASK_ID=process_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-27T13:19:05.540674+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-27T13:19:05.540674+00:00
[2022-06-27 13:19:10,663] {logging_mixin.py:115} INFO - ENTERED FUNCTION
[2022-06-27 13:19:10,664] {logging_mixin.py:115} INFO - gs://dtc-project-data_dtc-project-ritaafranco/raw/brooklyn.parquet
[2022-06-27 13:19:11,032] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-06-27 13:19:11,033] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-27 13:19:11,033] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 507, in send_command
    "Error while sending", e, proto.ERROR_ON_SEND)
py4j.protocol.Py4JNetworkError: Error while sending
[2022-06-27 13:19:11,035] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-27 13:19:15,486] {logging_mixin.py:115} INFO - df read -------------
[2022-06-27 13:19:17,704] {logging_mixin.py:115} INFO - Row(id='5e31d5503b85a2e63d634187', date_collected=datetime.date(2020, 1, 27), retailer_type='counter service', retailer_detail='ready-to-eat and prepackaged health food', food_type='ready-to-eat', food_detail='organic oatmeal', label_type='sticker', label_language='use by', label_date='2020-01-28', approximate_dollar_value=5.25, image_id='IMG_1872', collection_lat=40.69453, collection_long=-73.99447, label_explanation='')
[2022-06-27 13:19:19,051] {logging_mixin.py:115} INFO - ------------- 171 14
[2022-06-27 13:19:19,051] {logging_mixin.py:115} INFO - ['image_id', 'id']
[2022-06-27 13:19:19,962] {logging_mixin.py:115} INFO - ------------- 171 14
[2022-06-27 13:19:21,264] {logging_mixin.py:115} INFO - Row(id='5fc43370e12e1aa995d0b41c', date_collected=datetime.date(2020, 11, 20), retailer_type='chain grocer', retailer_detail='ready-to-eat, shelf-stable, frozen, and perishable food', food_type='perishable', food_detail='turkey drums', label_type='sticker', label_language='sell by', label_date='2020-11-20', approximate_dollar_value=2.24, image_id='IMG_3999', collection_lat=40.69789, collection_long=-73.99267, label_explanation='')
[2022-06-27 13:19:21,264] {python.py:173} INFO - Done. Returned value was: None
[2022-06-27 13:19:21,300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=process-food-waste-data, task_id=process_data_task, execution_date=20220627T131905, start_date=20220627T131910, end_date=20220627T131921
[2022-06-27 13:19:21,375] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:19:21,436] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
