[2022-06-23 17:38:43,994] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process-food-waste-data.spark_job manual__2022-06-23T17:38:14.026839+00:00 [queued]>
[2022-06-23 17:38:44,004] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process-food-waste-data.spark_job manual__2022-06-23T17:38:14.026839+00:00 [queued]>
[2022-06-23 17:38:44,004] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 17:38:44,004] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-23 17:38:44,004] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 17:38:44,021] {taskinstance.py:1377} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2022-06-23 17:38:14.026839+00:00
[2022-06-23 17:38:44,028] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-23 17:38:44,027] {standard_task_runner.py:52} INFO - Started process 304 to run task
[2022-06-23 17:38:44,031] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process-food-waste-data', 'spark_job', 'manual__2022-06-23T17:38:14.026839+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/02_data_process_dag.py', '--cfg-path', '/tmp/tmpy6g58lwu', '--error-file', '/tmp/tmppjiv0nt0']
[2022-06-23 17:38:44,031] {standard_task_runner.py:80} INFO - Job 283: Subtask spark_job
[2022-06-23 17:38:44,080] {task_command.py:370} INFO - Running <TaskInstance: process-food-waste-data.spark_job manual__2022-06-23T17:38:14.026839+00:00 [running]> on host d305947238c5
[2022-06-23 17:38:44,160] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process-food-waste-data
AIRFLOW_CTX_TASK_ID=spark_job
AIRFLOW_CTX_EXECUTION_DATE=2022-06-23T17:38:14.026839+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-23T17:38:14.026839+00:00
[2022-06-23 17:38:44,171] {spark_submit.py:204} INFO - Could not load connection string spark_project, defaulting to yarn
[2022-06-23 17:38:44,172] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 388, in submit
    spark_submit_cmd = self._build_spark_submit_command(application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 334, in _build_spark_submit_command
    self.log.info("Spark-Submit cmd: %s", self._mask_cmd(connection_cmd))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 246, in _mask_cmd
    ' '.join(connection_cmd),
TypeError: sequence item 11: expected str instance, list found
[2022-06-23 17:38:44,181] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=process-food-waste-data, task_id=spark_job, execution_date=20220623T173814, start_date=20220623T173843, end_date=20220623T173844
[2022-06-23 17:38:44,195] {standard_task_runner.py:97} ERROR - Failed to execute job 283 for task spark_job (sequence item 11: expected str instance, list found; 304)
[2022-06-23 17:38:44,202] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-23 17:38:44,243] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
