[2022-06-22 15:58:52,479] {processor.py:153} INFO - Started process (PID=7106) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:58:52,479] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 15:58:52,479] {logging_mixin.py:115} INFO - [2022-06-22 15:58:52,479] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:58:52,484] {logging_mixin.py:115} INFO - [2022-06-22 15:58:52,483] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 15:58:52,484] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:58:52,499] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 15:59:22,570] {processor.py:153} INFO - Started process (PID=7136) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:59:22,571] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 15:59:22,571] {logging_mixin.py:115} INFO - [2022-06-22 15:59:22,571] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:59:22,575] {logging_mixin.py:115} INFO - [2022-06-22 15:59:22,574] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 15:59:22,575] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:59:22,587] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.018 seconds
[2022-06-22 15:59:52,684] {processor.py:153} INFO - Started process (PID=7157) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:59:52,686] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 15:59:52,687] {logging_mixin.py:115} INFO - [2022-06-22 15:59:52,687] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:59:52,694] {logging_mixin.py:115} INFO - [2022-06-22 15:59:52,694] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 15:59:52,694] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 15:59:52,709] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.030 seconds
[2022-06-22 16:00:22,788] {processor.py:153} INFO - Started process (PID=7187) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:00:22,789] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:00:22,789] {logging_mixin.py:115} INFO - [2022-06-22 16:00:22,789] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:00:22,793] {logging_mixin.py:115} INFO - [2022-06-22 16:00:22,793] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:00:22,793] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:00:22,806] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:00:52,898] {processor.py:153} INFO - Started process (PID=7217) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:00:52,900] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:00:52,900] {logging_mixin.py:115} INFO - [2022-06-22 16:00:52,900] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:00:52,907] {logging_mixin.py:115} INFO - [2022-06-22 16:00:52,907] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:00:52,907] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:00:52,921] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.029 seconds
[2022-06-22 16:01:23,017] {processor.py:153} INFO - Started process (PID=7247) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:01:23,017] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:01:23,017] {logging_mixin.py:115} INFO - [2022-06-22 16:01:23,017] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:01:23,025] {logging_mixin.py:115} INFO - [2022-06-22 16:01:23,024] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:01:23,025] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:01:23,041] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.026 seconds
[2022-06-22 16:01:53,127] {processor.py:153} INFO - Started process (PID=7268) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:01:53,127] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:01:53,128] {logging_mixin.py:115} INFO - [2022-06-22 16:01:53,128] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:01:53,131] {logging_mixin.py:115} INFO - [2022-06-22 16:01:53,131] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:01:53,131] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:01:53,144] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:02:23,236] {processor.py:153} INFO - Started process (PID=7298) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:02:23,236] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:02:23,236] {logging_mixin.py:115} INFO - [2022-06-22 16:02:23,236] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:02:23,240] {logging_mixin.py:115} INFO - [2022-06-22 16:02:23,239] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:02:23,240] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:02:23,255] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.023 seconds
[2022-06-22 16:02:53,327] {processor.py:153} INFO - Started process (PID=7328) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:02:53,328] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:02:53,328] {logging_mixin.py:115} INFO - [2022-06-22 16:02:53,328] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:02:53,331] {logging_mixin.py:115} INFO - [2022-06-22 16:02:53,331] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:02:53,331] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:02:53,348] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.022 seconds
[2022-06-22 16:03:23,435] {processor.py:153} INFO - Started process (PID=7358) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:03:23,436] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:03:23,437] {logging_mixin.py:115} INFO - [2022-06-22 16:03:23,436] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:03:23,443] {logging_mixin.py:115} INFO - [2022-06-22 16:03:23,443] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:03:23,444] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:03:23,457] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.027 seconds
[2022-06-22 16:03:53,551] {processor.py:153} INFO - Started process (PID=7388) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:03:53,552] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:03:53,552] {logging_mixin.py:115} INFO - [2022-06-22 16:03:53,552] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:03:53,556] {logging_mixin.py:115} INFO - [2022-06-22 16:03:53,556] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:03:53,556] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:03:53,575] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:04:23,663] {processor.py:153} INFO - Started process (PID=7409) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:04:23,663] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:04:23,664] {logging_mixin.py:115} INFO - [2022-06-22 16:04:23,664] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:04:23,672] {logging_mixin.py:115} INFO - [2022-06-22 16:04:23,671] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:04:23,672] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:04:23,685] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.027 seconds
[2022-06-22 16:04:53,780] {processor.py:153} INFO - Started process (PID=7439) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:04:53,781] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:04:53,782] {logging_mixin.py:115} INFO - [2022-06-22 16:04:53,782] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:04:53,789] {logging_mixin.py:115} INFO - [2022-06-22 16:04:53,788] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:04:53,789] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:04:53,803] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.028 seconds
[2022-06-22 16:05:23,879] {processor.py:153} INFO - Started process (PID=7470) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:05:23,879] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:05:23,880] {logging_mixin.py:115} INFO - [2022-06-22 16:05:23,880] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:05:23,883] {logging_mixin.py:115} INFO - [2022-06-22 16:05:23,883] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:05:23,883] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:05:23,896] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:05:53,985] {processor.py:153} INFO - Started process (PID=7500) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:05:53,994] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:05:53,995] {logging_mixin.py:115} INFO - [2022-06-22 16:05:53,995] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:05:54,001] {logging_mixin.py:115} INFO - [2022-06-22 16:05:54,001] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:05:54,001] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:05:54,017] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.034 seconds
[2022-06-22 16:06:24,095] {processor.py:153} INFO - Started process (PID=7521) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:06:24,095] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:06:24,095] {logging_mixin.py:115} INFO - [2022-06-22 16:06:24,095] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:06:24,099] {logging_mixin.py:115} INFO - [2022-06-22 16:06:24,098] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:06:24,099] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:06:24,112] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.018 seconds
[2022-06-22 16:06:54,201] {processor.py:153} INFO - Started process (PID=7552) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:06:54,203] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:06:54,203] {logging_mixin.py:115} INFO - [2022-06-22 16:06:54,203] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:06:54,208] {logging_mixin.py:115} INFO - [2022-06-22 16:06:54,207] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:06:54,208] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:06:54,224] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.024 seconds
[2022-06-22 16:07:24,306] {processor.py:153} INFO - Started process (PID=7584) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:07:24,307] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:07:24,307] {logging_mixin.py:115} INFO - [2022-06-22 16:07:24,307] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:07:24,311] {logging_mixin.py:115} INFO - [2022-06-22 16:07:24,310] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:07:24,311] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:07:24,323] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:07:54,420] {processor.py:153} INFO - Started process (PID=7615) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:07:54,429] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:07:54,430] {logging_mixin.py:115} INFO - [2022-06-22 16:07:54,430] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:07:54,436] {logging_mixin.py:115} INFO - [2022-06-22 16:07:54,436] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:07:54,436] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:07:54,452] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.034 seconds
[2022-06-22 16:08:24,540] {processor.py:153} INFO - Started process (PID=7645) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:08:24,540] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:08:24,540] {logging_mixin.py:115} INFO - [2022-06-22 16:08:24,540] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:08:24,544] {logging_mixin.py:115} INFO - [2022-06-22 16:08:24,544] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:08:24,544] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:08:24,559] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:08:54,659] {processor.py:153} INFO - Started process (PID=7666) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:08:54,660] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:08:54,661] {logging_mixin.py:115} INFO - [2022-06-22 16:08:54,661] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:08:54,666] {logging_mixin.py:115} INFO - [2022-06-22 16:08:54,666] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:08:54,666] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:08:54,681] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.024 seconds
[2022-06-22 16:09:24,772] {processor.py:153} INFO - Started process (PID=7696) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:09:24,772] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:09:24,772] {logging_mixin.py:115} INFO - [2022-06-22 16:09:24,772] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:09:24,776] {logging_mixin.py:115} INFO - [2022-06-22 16:09:24,776] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:09:24,776] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:09:24,790] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:09:54,869] {processor.py:153} INFO - Started process (PID=7726) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:09:54,878] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:09:54,879] {logging_mixin.py:115} INFO - [2022-06-22 16:09:54,879] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:09:54,889] {logging_mixin.py:115} INFO - [2022-06-22 16:09:54,889] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:09:54,890] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:09:54,904] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.039 seconds
[2022-06-22 16:10:25,002] {processor.py:153} INFO - Started process (PID=7756) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:10:25,002] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:10:25,003] {logging_mixin.py:115} INFO - [2022-06-22 16:10:25,003] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:10:25,006] {logging_mixin.py:115} INFO - [2022-06-22 16:10:25,006] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:10:25,007] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:10:25,018] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:10:55,105] {processor.py:153} INFO - Started process (PID=7777) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:10:55,114] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:10:55,115] {logging_mixin.py:115} INFO - [2022-06-22 16:10:55,115] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:10:55,125] {logging_mixin.py:115} INFO - [2022-06-22 16:10:55,124] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:10:55,125] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:10:55,143] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.040 seconds
[2022-06-22 16:11:25,242] {processor.py:153} INFO - Started process (PID=7807) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:11:25,242] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:11:25,242] {logging_mixin.py:115} INFO - [2022-06-22 16:11:25,242] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:11:25,246] {logging_mixin.py:115} INFO - [2022-06-22 16:11:25,245] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:11:25,246] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:11:25,259] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:11:55,348] {processor.py:153} INFO - Started process (PID=7838) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:11:55,349] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:11:55,350] {logging_mixin.py:115} INFO - [2022-06-22 16:11:55,350] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:11:55,356] {logging_mixin.py:115} INFO - [2022-06-22 16:11:55,355] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:11:55,356] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:11:55,371] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:12:25,456] {processor.py:153} INFO - Started process (PID=7868) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:12:25,457] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:12:25,457] {logging_mixin.py:115} INFO - [2022-06-22 16:12:25,457] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:12:25,461] {logging_mixin.py:115} INFO - [2022-06-22 16:12:25,460] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:12:25,461] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:12:25,477] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.022 seconds
[2022-06-22 16:12:55,564] {processor.py:153} INFO - Started process (PID=7898) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:12:55,565] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:12:55,566] {logging_mixin.py:115} INFO - [2022-06-22 16:12:55,566] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:12:55,574] {logging_mixin.py:115} INFO - [2022-06-22 16:12:55,573] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:12:55,574] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:12:55,589] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.031 seconds
[2022-06-22 16:13:25,686] {processor.py:153} INFO - Started process (PID=7919) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:13:25,686] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:13:25,687] {logging_mixin.py:115} INFO - [2022-06-22 16:13:25,687] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:13:25,690] {logging_mixin.py:115} INFO - [2022-06-22 16:13:25,690] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:13:25,690] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:13:25,707] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.024 seconds
[2022-06-22 16:13:55,799] {processor.py:153} INFO - Started process (PID=7949) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:13:55,800] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:13:55,801] {logging_mixin.py:115} INFO - [2022-06-22 16:13:55,801] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:13:55,804] {logging_mixin.py:115} INFO - [2022-06-22 16:13:55,804] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:13:55,804] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:13:55,818] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:14:25,905] {processor.py:153} INFO - Started process (PID=7979) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:14:25,905] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:14:25,906] {logging_mixin.py:115} INFO - [2022-06-22 16:14:25,906] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:14:25,909] {logging_mixin.py:115} INFO - [2022-06-22 16:14:25,909] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:14:25,909] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:14:25,923] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:14:56,014] {processor.py:153} INFO - Started process (PID=8009) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:14:56,016] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:14:56,017] {logging_mixin.py:115} INFO - [2022-06-22 16:14:56,017] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:14:56,026] {logging_mixin.py:115} INFO - [2022-06-22 16:14:56,025] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:14:56,026] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:14:56,041] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.032 seconds
[2022-06-22 16:15:26,118] {processor.py:153} INFO - Started process (PID=8041) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:15:26,118] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:15:26,119] {logging_mixin.py:115} INFO - [2022-06-22 16:15:26,118] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:15:26,122] {logging_mixin.py:115} INFO - [2022-06-22 16:15:26,122] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:15:26,122] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:15:26,136] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:15:56,222] {processor.py:153} INFO - Started process (PID=8062) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:15:56,225] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:15:56,226] {logging_mixin.py:115} INFO - [2022-06-22 16:15:56,226] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:15:56,230] {logging_mixin.py:115} INFO - [2022-06-22 16:15:56,230] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:15:56,230] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:15:56,243] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.027 seconds
[2022-06-22 16:16:26,323] {processor.py:153} INFO - Started process (PID=8092) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:16:26,323] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:16:26,323] {logging_mixin.py:115} INFO - [2022-06-22 16:16:26,323] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:16:26,327] {logging_mixin.py:115} INFO - [2022-06-22 16:16:26,327] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:16:26,327] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:16:26,340] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:16:56,423] {processor.py:153} INFO - Started process (PID=8122) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:16:56,425] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:16:56,425] {logging_mixin.py:115} INFO - [2022-06-22 16:16:56,425] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:16:56,431] {logging_mixin.py:115} INFO - [2022-06-22 16:16:56,431] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:16:56,431] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:16:56,444] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.023 seconds
[2022-06-22 16:17:26,538] {processor.py:153} INFO - Started process (PID=8153) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:17:26,538] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:17:26,538] {logging_mixin.py:115} INFO - [2022-06-22 16:17:26,538] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:17:26,543] {logging_mixin.py:115} INFO - [2022-06-22 16:17:26,542] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:17:26,543] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:17:26,556] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:17:56,638] {processor.py:153} INFO - Started process (PID=8174) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:17:56,639] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:17:56,640] {logging_mixin.py:115} INFO - [2022-06-22 16:17:56,639] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:17:56,649] {logging_mixin.py:115} INFO - [2022-06-22 16:17:56,648] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:17:56,649] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:17:56,668] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.033 seconds
[2022-06-22 16:18:26,751] {processor.py:153} INFO - Started process (PID=8204) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:18:26,751] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:18:26,751] {logging_mixin.py:115} INFO - [2022-06-22 16:18:26,751] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:18:26,755] {logging_mixin.py:115} INFO - [2022-06-22 16:18:26,755] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:18:26,755] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:18:26,769] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:18:56,868] {processor.py:153} INFO - Started process (PID=8234) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:18:56,868] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:18:56,868] {logging_mixin.py:115} INFO - [2022-06-22 16:18:56,868] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:18:56,872] {logging_mixin.py:115} INFO - [2022-06-22 16:18:56,871] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:18:56,872] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:18:56,886] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:19:26,978] {processor.py:153} INFO - Started process (PID=8265) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:19:26,978] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:19:26,979] {logging_mixin.py:115} INFO - [2022-06-22 16:19:26,979] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:19:26,987] {logging_mixin.py:115} INFO - [2022-06-22 16:19:26,986] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:19:26,987] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:19:27,000] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.027 seconds
[2022-06-22 16:19:57,084] {processor.py:153} INFO - Started process (PID=8295) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:19:57,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:19:57,085] {logging_mixin.py:115} INFO - [2022-06-22 16:19:57,085] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:19:57,089] {logging_mixin.py:115} INFO - [2022-06-22 16:19:57,088] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:19:57,089] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:19:57,103] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:20:27,182] {processor.py:153} INFO - Started process (PID=8316) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:20:27,182] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:20:27,182] {logging_mixin.py:115} INFO - [2022-06-22 16:20:27,182] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:20:27,186] {logging_mixin.py:115} INFO - [2022-06-22 16:20:27,185] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:20:27,186] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:20:27,199] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:20:57,289] {processor.py:153} INFO - Started process (PID=8346) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:20:57,291] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:20:57,291] {logging_mixin.py:115} INFO - [2022-06-22 16:20:57,291] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:20:57,295] {logging_mixin.py:115} INFO - [2022-06-22 16:20:57,295] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:20:57,295] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:20:57,309] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:21:27,397] {processor.py:153} INFO - Started process (PID=8376) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:21:27,397] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:21:27,397] {logging_mixin.py:115} INFO - [2022-06-22 16:21:27,397] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:21:27,401] {logging_mixin.py:115} INFO - [2022-06-22 16:21:27,400] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:21:27,401] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:21:27,420] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.027 seconds
[2022-06-22 16:21:57,515] {processor.py:153} INFO - Started process (PID=8406) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:21:57,517] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:21:57,517] {logging_mixin.py:115} INFO - [2022-06-22 16:21:57,517] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:21:57,524] {logging_mixin.py:115} INFO - [2022-06-22 16:21:57,523] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:21:57,524] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:21:57,538] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:22:27,620] {processor.py:153} INFO - Started process (PID=8428) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:22:27,620] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:22:27,621] {logging_mixin.py:115} INFO - [2022-06-22 16:22:27,621] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:22:27,624] {logging_mixin.py:115} INFO - [2022-06-22 16:22:27,624] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:22:27,624] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:22:27,639] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:22:57,733] {processor.py:153} INFO - Started process (PID=8458) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:22:57,735] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:22:57,735] {logging_mixin.py:115} INFO - [2022-06-22 16:22:57,735] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:22:57,745] {logging_mixin.py:115} INFO - [2022-06-22 16:22:57,744] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:22:57,745] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:22:57,762] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.031 seconds
[2022-06-22 16:23:27,853] {processor.py:153} INFO - Started process (PID=8488) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:23:27,854] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:23:27,854] {logging_mixin.py:115} INFO - [2022-06-22 16:23:27,854] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:23:27,857] {logging_mixin.py:115} INFO - [2022-06-22 16:23:27,857] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:23:27,858] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:23:27,871] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:23:57,968] {processor.py:153} INFO - Started process (PID=8518) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:23:57,970] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:23:57,970] {logging_mixin.py:115} INFO - [2022-06-22 16:23:57,970] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:23:57,978] {logging_mixin.py:115} INFO - [2022-06-22 16:23:57,978] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:23:57,979] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:23:57,995] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.030 seconds
[2022-06-22 16:24:28,076] {processor.py:153} INFO - Started process (PID=8548) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:24:28,076] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:24:28,076] {logging_mixin.py:115} INFO - [2022-06-22 16:24:28,076] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:24:28,080] {logging_mixin.py:115} INFO - [2022-06-22 16:24:28,079] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:24:28,080] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:24:28,093] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:24:58,189] {processor.py:153} INFO - Started process (PID=8569) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:24:58,191] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:24:58,191] {logging_mixin.py:115} INFO - [2022-06-22 16:24:58,191] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:24:58,198] {logging_mixin.py:115} INFO - [2022-06-22 16:24:58,197] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:24:58,198] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:24:58,212] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:25:28,302] {processor.py:153} INFO - Started process (PID=8599) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:25:28,302] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:25:28,303] {logging_mixin.py:115} INFO - [2022-06-22 16:25:28,303] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:25:28,306] {logging_mixin.py:115} INFO - [2022-06-22 16:25:28,306] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:25:28,306] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:25:28,319] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.018 seconds
[2022-06-22 16:25:58,396] {processor.py:153} INFO - Started process (PID=8631) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:25:58,398] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:25:58,398] {logging_mixin.py:115} INFO - [2022-06-22 16:25:58,398] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:25:58,401] {logging_mixin.py:115} INFO - [2022-06-22 16:25:58,401] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:25:58,402] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:25:58,415] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:26:28,501] {processor.py:153} INFO - Started process (PID=8662) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:26:28,501] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:26:28,502] {logging_mixin.py:115} INFO - [2022-06-22 16:26:28,502] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:26:28,505] {logging_mixin.py:115} INFO - [2022-06-22 16:26:28,505] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:26:28,505] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:26:28,518] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.018 seconds
[2022-06-22 16:26:58,606] {processor.py:153} INFO - Started process (PID=8683) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:26:58,608] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:26:58,608] {logging_mixin.py:115} INFO - [2022-06-22 16:26:58,608] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:26:58,612] {logging_mixin.py:115} INFO - [2022-06-22 16:26:58,611] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:26:58,612] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:26:58,626] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.022 seconds
[2022-06-22 16:27:28,689] {processor.py:153} INFO - Started process (PID=8713) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:27:28,689] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:27:28,690] {logging_mixin.py:115} INFO - [2022-06-22 16:27:28,690] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:27:28,693] {logging_mixin.py:115} INFO - [2022-06-22 16:27:28,692] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:27:28,693] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:27:28,708] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.022 seconds
[2022-06-22 16:27:58,796] {processor.py:153} INFO - Started process (PID=8743) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:27:58,796] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:27:58,796] {logging_mixin.py:115} INFO - [2022-06-22 16:27:58,796] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:27:58,800] {logging_mixin.py:115} INFO - [2022-06-22 16:27:58,799] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:27:58,800] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:27:58,813] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:28:28,905] {processor.py:153} INFO - Started process (PID=8773) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:28:28,905] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:28:28,906] {logging_mixin.py:115} INFO - [2022-06-22 16:28:28,906] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:28:28,909] {logging_mixin.py:115} INFO - [2022-06-22 16:28:28,908] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:28:28,909] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:28:28,929] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:28:59,046] {processor.py:153} INFO - Started process (PID=8803) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:28:59,047] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:28:59,047] {logging_mixin.py:115} INFO - [2022-06-22 16:28:59,047] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:28:59,050] {logging_mixin.py:115} INFO - [2022-06-22 16:28:59,050] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:28:59,050] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:28:59,064] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:29:29,145] {processor.py:153} INFO - Started process (PID=8824) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:29:29,145] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:29:29,145] {logging_mixin.py:115} INFO - [2022-06-22 16:29:29,145] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:29:29,149] {logging_mixin.py:115} INFO - [2022-06-22 16:29:29,148] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:29:29,149] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:29:29,162] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:29:59,257] {processor.py:153} INFO - Started process (PID=8854) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:29:59,266] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:29:59,266] {logging_mixin.py:115} INFO - [2022-06-22 16:29:59,266] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:29:59,270] {logging_mixin.py:115} INFO - [2022-06-22 16:29:59,269] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:29:59,270] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:29:59,283] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.029 seconds
[2022-06-22 16:30:29,367] {processor.py:153} INFO - Started process (PID=8884) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:30:29,367] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:30:29,367] {logging_mixin.py:115} INFO - [2022-06-22 16:30:29,367] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:30:29,371] {logging_mixin.py:115} INFO - [2022-06-22 16:30:29,371] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:30:29,371] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:30:29,389] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:30:59,478] {processor.py:153} INFO - Started process (PID=8914) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:30:59,486] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:30:59,487] {logging_mixin.py:115} INFO - [2022-06-22 16:30:59,487] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:30:59,490] {logging_mixin.py:115} INFO - [2022-06-22 16:30:59,490] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:30:59,490] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:30:59,505] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.029 seconds
[2022-06-22 16:31:29,581] {processor.py:153} INFO - Started process (PID=8945) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:31:29,582] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:31:29,582] {logging_mixin.py:115} INFO - [2022-06-22 16:31:29,582] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:31:29,585] {logging_mixin.py:115} INFO - [2022-06-22 16:31:29,585] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:31:29,585] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:31:29,599] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:31:59,689] {processor.py:153} INFO - Started process (PID=8966) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:31:59,699] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:31:59,699] {logging_mixin.py:115} INFO - [2022-06-22 16:31:59,699] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:31:59,710] {logging_mixin.py:115} INFO - [2022-06-22 16:31:59,709] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:31:59,710] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:31:59,730] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.046 seconds
[2022-06-22 16:32:29,827] {processor.py:153} INFO - Started process (PID=8997) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:32:29,827] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:32:29,827] {logging_mixin.py:115} INFO - [2022-06-22 16:32:29,827] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:32:29,831] {logging_mixin.py:115} INFO - [2022-06-22 16:32:29,831] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:32:29,831] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:32:29,845] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:32:59,916] {processor.py:153} INFO - Started process (PID=9027) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:32:59,917] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:32:59,918] {logging_mixin.py:115} INFO - [2022-06-22 16:32:59,918] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:32:59,922] {logging_mixin.py:115} INFO - [2022-06-22 16:32:59,922] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:32:59,922] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:32:59,934] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:33:30,027] {processor.py:153} INFO - Started process (PID=9057) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:33:30,028] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:33:30,028] {logging_mixin.py:115} INFO - [2022-06-22 16:33:30,028] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:33:30,031] {logging_mixin.py:115} INFO - [2022-06-22 16:33:30,031] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:33:30,032] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:33:30,044] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.018 seconds
[2022-06-22 16:34:00,129] {processor.py:153} INFO - Started process (PID=9087) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:34:00,131] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:34:00,131] {logging_mixin.py:115} INFO - [2022-06-22 16:34:00,131] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:34:00,135] {logging_mixin.py:115} INFO - [2022-06-22 16:34:00,135] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:34:00,135] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:34:00,149] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:34:30,251] {processor.py:153} INFO - Started process (PID=9108) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:34:30,251] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:34:30,251] {logging_mixin.py:115} INFO - [2022-06-22 16:34:30,251] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:34:30,255] {logging_mixin.py:115} INFO - [2022-06-22 16:34:30,254] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:34:30,255] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:34:30,273] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.024 seconds
[2022-06-22 16:35:00,353] {processor.py:153} INFO - Started process (PID=9139) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:35:00,355] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:35:00,355] {logging_mixin.py:115} INFO - [2022-06-22 16:35:00,355] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:35:00,362] {logging_mixin.py:115} INFO - [2022-06-22 16:35:00,362] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:35:00,362] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:35:00,377] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.026 seconds
[2022-06-22 16:35:30,468] {processor.py:153} INFO - Started process (PID=9169) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:35:30,468] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:35:30,468] {logging_mixin.py:115} INFO - [2022-06-22 16:35:30,468] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:35:30,473] {logging_mixin.py:115} INFO - [2022-06-22 16:35:30,473] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:35:30,473] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:35:30,491] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:36:00,590] {processor.py:153} INFO - Started process (PID=9199) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:36:00,590] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:36:00,590] {logging_mixin.py:115} INFO - [2022-06-22 16:36:00,590] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:36:00,594] {logging_mixin.py:115} INFO - [2022-06-22 16:36:00,594] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:36:00,594] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:36:00,611] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.024 seconds
[2022-06-22 16:36:30,697] {processor.py:153} INFO - Started process (PID=9220) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:36:30,697] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:36:30,697] {logging_mixin.py:115} INFO - [2022-06-22 16:36:30,697] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:36:30,701] {logging_mixin.py:115} INFO - [2022-06-22 16:36:30,700] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:36:30,701] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:36:30,720] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:37:00,815] {processor.py:153} INFO - Started process (PID=9250) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:37:00,817] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:37:00,817] {logging_mixin.py:115} INFO - [2022-06-22 16:37:00,817] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:37:00,821] {logging_mixin.py:115} INFO - [2022-06-22 16:37:00,821] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:37:00,821] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:37:00,835] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.023 seconds
[2022-06-22 16:37:30,925] {processor.py:153} INFO - Started process (PID=9281) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:37:30,925] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:37:30,926] {logging_mixin.py:115} INFO - [2022-06-22 16:37:30,926] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:37:30,930] {logging_mixin.py:115} INFO - [2022-06-22 16:37:30,930] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:37:30,930] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:37:30,945] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.023 seconds
[2022-06-22 16:38:01,031] {processor.py:153} INFO - Started process (PID=9312) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:38:01,032] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:38:01,032] {logging_mixin.py:115} INFO - [2022-06-22 16:38:01,032] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:38:01,037] {logging_mixin.py:115} INFO - [2022-06-22 16:38:01,036] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:38:01,037] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:38:01,050] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.022 seconds
[2022-06-22 16:38:31,142] {processor.py:153} INFO - Started process (PID=9342) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:38:31,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:38:31,142] {logging_mixin.py:115} INFO - [2022-06-22 16:38:31,142] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:38:31,146] {logging_mixin.py:115} INFO - [2022-06-22 16:38:31,146] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:38:31,146] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:38:31,165] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.027 seconds
[2022-06-22 16:39:01,289] {processor.py:153} INFO - Started process (PID=9363) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:39:01,290] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:39:01,291] {logging_mixin.py:115} INFO - [2022-06-22 16:39:01,290] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:39:01,294] {logging_mixin.py:115} INFO - [2022-06-22 16:39:01,294] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:39:01,294] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:39:01,311] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.024 seconds
[2022-06-22 16:39:31,397] {processor.py:153} INFO - Started process (PID=9394) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:39:31,397] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:39:31,397] {logging_mixin.py:115} INFO - [2022-06-22 16:39:31,397] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:39:31,401] {logging_mixin.py:115} INFO - [2022-06-22 16:39:31,400] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:39:31,401] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:39:31,418] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:40:01,499] {processor.py:153} INFO - Started process (PID=9425) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:40:01,500] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:40:01,500] {logging_mixin.py:115} INFO - [2022-06-22 16:40:01,500] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:40:01,504] {logging_mixin.py:115} INFO - [2022-06-22 16:40:01,504] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:40:01,505] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:40:01,523] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:40:31,606] {processor.py:153} INFO - Started process (PID=9455) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:40:31,606] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:40:31,607] {logging_mixin.py:115} INFO - [2022-06-22 16:40:31,607] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:40:31,613] {logging_mixin.py:115} INFO - [2022-06-22 16:40:31,612] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:40:31,613] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:40:31,628] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.026 seconds
[2022-06-22 16:41:01,716] {processor.py:153} INFO - Started process (PID=9483) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:41:01,716] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:41:01,717] {logging_mixin.py:115} INFO - [2022-06-22 16:41:01,716] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:41:01,720] {logging_mixin.py:115} INFO - [2022-06-22 16:41:01,720] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:41:01,720] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:41:01,733] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:41:31,816] {processor.py:153} INFO - Started process (PID=9506) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:41:31,816] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:41:31,816] {logging_mixin.py:115} INFO - [2022-06-22 16:41:31,816] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:41:31,820] {logging_mixin.py:115} INFO - [2022-06-22 16:41:31,819] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:41:31,820] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:41:31,834] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:42:01,907] {processor.py:153} INFO - Started process (PID=9536) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:42:01,908] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:42:01,908] {logging_mixin.py:115} INFO - [2022-06-22 16:42:01,908] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:42:01,912] {logging_mixin.py:115} INFO - [2022-06-22 16:42:01,912] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:42:01,913] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:42:01,930] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.024 seconds
[2022-06-22 16:42:32,017] {processor.py:153} INFO - Started process (PID=9566) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:42:32,018] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:42:32,018] {logging_mixin.py:115} INFO - [2022-06-22 16:42:32,018] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:42:32,021] {logging_mixin.py:115} INFO - [2022-06-22 16:42:32,021] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:42:32,021] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:42:32,037] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:43:02,127] {processor.py:153} INFO - Started process (PID=9597) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:43:02,128] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:43:02,128] {logging_mixin.py:115} INFO - [2022-06-22 16:43:02,128] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:43:02,132] {logging_mixin.py:115} INFO - [2022-06-22 16:43:02,131] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:43:02,132] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:43:02,145] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:43:32,254] {processor.py:153} INFO - Started process (PID=9618) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:43:32,255] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:43:32,255] {logging_mixin.py:115} INFO - [2022-06-22 16:43:32,255] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:43:32,258] {logging_mixin.py:115} INFO - [2022-06-22 16:43:32,258] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:43:32,258] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:43:32,272] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:44:02,353] {processor.py:153} INFO - Started process (PID=9648) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:44:02,362] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:44:02,362] {logging_mixin.py:115} INFO - [2022-06-22 16:44:02,362] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:44:02,371] {logging_mixin.py:115} INFO - [2022-06-22 16:44:02,370] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:44:02,371] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:44:02,387] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.036 seconds
[2022-06-22 16:44:32,482] {processor.py:153} INFO - Started process (PID=9678) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:44:32,482] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:44:32,482] {logging_mixin.py:115} INFO - [2022-06-22 16:44:32,482] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:44:32,490] {logging_mixin.py:115} INFO - [2022-06-22 16:44:32,489] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:44:32,490] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:44:32,505] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:45:02,598] {processor.py:153} INFO - Started process (PID=9708) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:45:02,599] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:45:02,599] {logging_mixin.py:115} INFO - [2022-06-22 16:45:02,599] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:45:02,603] {logging_mixin.py:115} INFO - [2022-06-22 16:45:02,602] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:45:02,603] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:45:02,616] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.022 seconds
[2022-06-22 16:45:32,707] {processor.py:153} INFO - Started process (PID=9736) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:45:32,707] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:45:32,707] {logging_mixin.py:115} INFO - [2022-06-22 16:45:32,707] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:45:32,711] {logging_mixin.py:115} INFO - [2022-06-22 16:45:32,710] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:45:32,711] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:45:32,724] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:46:02,812] {processor.py:153} INFO - Started process (PID=9759) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:46:02,812] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:46:02,812] {logging_mixin.py:115} INFO - [2022-06-22 16:46:02,812] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:46:02,816] {logging_mixin.py:115} INFO - [2022-06-22 16:46:02,815] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:46:02,816] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:46:02,829] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:46:32,924] {processor.py:153} INFO - Started process (PID=9789) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:46:32,924] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:46:32,925] {logging_mixin.py:115} INFO - [2022-06-22 16:46:32,925] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:46:32,932] {logging_mixin.py:115} INFO - [2022-06-22 16:46:32,932] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:46:32,933] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:46:32,948] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.029 seconds
[2022-06-22 16:47:03,028] {processor.py:153} INFO - Started process (PID=9820) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:47:03,030] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:47:03,030] {logging_mixin.py:115} INFO - [2022-06-22 16:47:03,030] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:47:03,033] {logging_mixin.py:115} INFO - [2022-06-22 16:47:03,033] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:47:03,033] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:47:03,050] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.023 seconds
[2022-06-22 16:47:33,155] {processor.py:153} INFO - Started process (PID=9850) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:47:33,155] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:47:33,155] {logging_mixin.py:115} INFO - [2022-06-22 16:47:33,155] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:47:33,159] {logging_mixin.py:115} INFO - [2022-06-22 16:47:33,158] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:47:33,159] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:47:33,172] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:48:03,260] {processor.py:153} INFO - Started process (PID=9871) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:48:03,262] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:48:03,263] {logging_mixin.py:115} INFO - [2022-06-22 16:48:03,263] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:48:03,272] {logging_mixin.py:115} INFO - [2022-06-22 16:48:03,271] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:48:03,272] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:48:03,288] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.031 seconds
[2022-06-22 16:48:33,398] {processor.py:153} INFO - Started process (PID=9901) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:48:33,398] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:48:33,399] {logging_mixin.py:115} INFO - [2022-06-22 16:48:33,399] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:48:33,405] {logging_mixin.py:115} INFO - [2022-06-22 16:48:33,405] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:48:33,406] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:48:33,423] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.028 seconds
[2022-06-22 16:49:03,509] {processor.py:153} INFO - Started process (PID=9931) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:49:03,511] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:49:03,511] {logging_mixin.py:115} INFO - [2022-06-22 16:49:03,511] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:49:03,515] {logging_mixin.py:115} INFO - [2022-06-22 16:49:03,514] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:49:03,515] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:49:03,529] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.022 seconds
[2022-06-22 16:49:33,605] {processor.py:153} INFO - Started process (PID=9961) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:49:33,605] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:49:33,606] {logging_mixin.py:115} INFO - [2022-06-22 16:49:33,606] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:49:33,609] {logging_mixin.py:115} INFO - [2022-06-22 16:49:33,609] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:49:33,609] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:49:33,623] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:50:03,724] {processor.py:153} INFO - Started process (PID=9991) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:50:03,724] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:50:03,724] {logging_mixin.py:115} INFO - [2022-06-22 16:50:03,724] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:50:03,728] {logging_mixin.py:115} INFO - [2022-06-22 16:50:03,728] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:50:03,728] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:50:03,743] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.022 seconds
[2022-06-22 16:50:33,829] {processor.py:153} INFO - Started process (PID=10012) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:50:33,829] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:50:33,829] {logging_mixin.py:115} INFO - [2022-06-22 16:50:33,829] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:50:33,833] {logging_mixin.py:115} INFO - [2022-06-22 16:50:33,833] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:50:33,833] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:50:33,847] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:51:03,947] {processor.py:153} INFO - Started process (PID=10043) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:51:03,949] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:51:03,950] {logging_mixin.py:115} INFO - [2022-06-22 16:51:03,950] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:51:03,956] {logging_mixin.py:115} INFO - [2022-06-22 16:51:03,956] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:51:03,957] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:51:03,971] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.026 seconds
[2022-06-22 16:51:34,061] {processor.py:153} INFO - Started process (PID=10073) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:51:34,062] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:51:34,062] {logging_mixin.py:115} INFO - [2022-06-22 16:51:34,062] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:51:34,066] {logging_mixin.py:115} INFO - [2022-06-22 16:51:34,065] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:51:34,066] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:51:34,080] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:52:04,172] {processor.py:153} INFO - Started process (PID=10104) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:52:04,174] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:52:04,174] {logging_mixin.py:115} INFO - [2022-06-22 16:52:04,174] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:52:04,184] {logging_mixin.py:115} INFO - [2022-06-22 16:52:04,183] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:52:04,184] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:52:04,199] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.029 seconds
[2022-06-22 16:52:34,283] {processor.py:153} INFO - Started process (PID=10125) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:52:34,283] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:52:34,283] {logging_mixin.py:115} INFO - [2022-06-22 16:52:34,283] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:52:34,287] {logging_mixin.py:115} INFO - [2022-06-22 16:52:34,287] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:52:34,287] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:52:34,300] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:53:04,387] {processor.py:153} INFO - Started process (PID=10156) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:53:04,388] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:53:04,389] {logging_mixin.py:115} INFO - [2022-06-22 16:53:04,389] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:53:04,392] {logging_mixin.py:115} INFO - [2022-06-22 16:53:04,392] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:53:04,393] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:53:04,406] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.023 seconds
[2022-06-22 16:53:34,495] {processor.py:153} INFO - Started process (PID=10187) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:53:34,495] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:53:34,495] {logging_mixin.py:115} INFO - [2022-06-22 16:53:34,495] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:53:34,499] {logging_mixin.py:115} INFO - [2022-06-22 16:53:34,499] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:53:34,499] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:53:34,513] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:54:04,605] {processor.py:153} INFO - Started process (PID=10217) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:54:04,605] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:54:04,606] {logging_mixin.py:115} INFO - [2022-06-22 16:54:04,606] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:54:04,609] {logging_mixin.py:115} INFO - [2022-06-22 16:54:04,609] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:54:04,609] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:54:04,623] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.020 seconds
[2022-06-22 16:54:34,728] {processor.py:153} INFO - Started process (PID=10247) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:54:34,729] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:54:34,730] {logging_mixin.py:115} INFO - [2022-06-22 16:54:34,729] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:54:34,738] {logging_mixin.py:115} INFO - [2022-06-22 16:54:34,738] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:54:34,739] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:54:34,757] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.034 seconds
[2022-06-22 16:55:04,835] {processor.py:153} INFO - Started process (PID=10269) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:55:04,836] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:55:04,836] {logging_mixin.py:115} INFO - [2022-06-22 16:55:04,836] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:55:04,840] {logging_mixin.py:115} INFO - [2022-06-22 16:55:04,840] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:55:04,841] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:55:04,858] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:55:34,949] {processor.py:153} INFO - Started process (PID=10299) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:55:34,949] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:55:34,949] {logging_mixin.py:115} INFO - [2022-06-22 16:55:34,949] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:55:34,953] {logging_mixin.py:115} INFO - [2022-06-22 16:55:34,952] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:55:34,953] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:55:34,972] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 16:56:05,057] {processor.py:153} INFO - Started process (PID=10329) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:56:05,057] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:56:05,057] {logging_mixin.py:115} INFO - [2022-06-22 16:56:05,057] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:56:05,061] {logging_mixin.py:115} INFO - [2022-06-22 16:56:05,061] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:56:05,061] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:56:05,074] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 16:56:35,166] {processor.py:153} INFO - Started process (PID=10359) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:56:35,166] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:56:35,167] {logging_mixin.py:115} INFO - [2022-06-22 16:56:35,167] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:56:35,171] {logging_mixin.py:115} INFO - [2022-06-22 16:56:35,171] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:56:35,171] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:56:35,190] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.026 seconds
[2022-06-22 16:57:05,281] {processor.py:153} INFO - Started process (PID=10390) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:57:05,283] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:57:05,283] {logging_mixin.py:115} INFO - [2022-06-22 16:57:05,283] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:57:05,287] {logging_mixin.py:115} INFO - [2022-06-22 16:57:05,286] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:57:05,287] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:57:05,300] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 16:57:35,396] {processor.py:153} INFO - Started process (PID=10411) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:57:35,397] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:57:35,397] {logging_mixin.py:115} INFO - [2022-06-22 16:57:35,397] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:57:35,400] {logging_mixin.py:115} INFO - [2022-06-22 16:57:35,400] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:57:35,401] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:57:35,419] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.024 seconds
[2022-06-22 16:58:05,505] {processor.py:153} INFO - Started process (PID=10442) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:58:05,507] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:58:05,508] {logging_mixin.py:115} INFO - [2022-06-22 16:58:05,508] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:58:05,515] {logging_mixin.py:115} INFO - [2022-06-22 16:58:05,514] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:58:05,515] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:58:05,531] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.027 seconds
[2022-06-22 16:58:35,617] {processor.py:153} INFO - Started process (PID=10473) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:58:35,617] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:58:35,617] {logging_mixin.py:115} INFO - [2022-06-22 16:58:35,617] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:58:35,621] {logging_mixin.py:115} INFO - [2022-06-22 16:58:35,620] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:58:35,621] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:58:35,641] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.028 seconds
[2022-06-22 16:59:05,759] {processor.py:153} INFO - Started process (PID=10504) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:59:05,761] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:59:05,761] {logging_mixin.py:115} INFO - [2022-06-22 16:59:05,761] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:59:05,770] {logging_mixin.py:115} INFO - [2022-06-22 16:59:05,770] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:59:05,771] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:59:05,791] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.036 seconds
[2022-06-22 16:59:35,882] {processor.py:153} INFO - Started process (PID=10525) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:59:35,882] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 16:59:35,883] {logging_mixin.py:115} INFO - [2022-06-22 16:59:35,883] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:59:35,886] {logging_mixin.py:115} INFO - [2022-06-22 16:59:35,886] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 16:59:35,886] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 16:59:35,907] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.028 seconds
[2022-06-22 17:00:06,007] {processor.py:153} INFO - Started process (PID=10555) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:00:06,008] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 17:00:06,009] {logging_mixin.py:115} INFO - [2022-06-22 17:00:06,009] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:00:06,017] {logging_mixin.py:115} INFO - [2022-06-22 17:00:06,016] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 17:00:06,017] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:00:06,032] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.031 seconds
[2022-06-22 17:00:36,126] {processor.py:153} INFO - Started process (PID=10586) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:00:36,126] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 17:00:36,127] {logging_mixin.py:115} INFO - [2022-06-22 17:00:36,127] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:00:36,131] {logging_mixin.py:115} INFO - [2022-06-22 17:00:36,131] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 17:00:36,131] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:00:36,149] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.025 seconds
[2022-06-22 17:01:06,239] {processor.py:153} INFO - Started process (PID=10617) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:01:06,241] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 17:01:06,242] {logging_mixin.py:115} INFO - [2022-06-22 17:01:06,241] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:01:06,248] {logging_mixin.py:115} INFO - [2022-06-22 17:01:06,248] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 17:01:06,248] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:01:06,267] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.030 seconds
[2022-06-22 17:01:36,351] {processor.py:153} INFO - Started process (PID=10647) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:01:36,352] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 17:01:36,352] {logging_mixin.py:115} INFO - [2022-06-22 17:01:36,352] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:01:36,356] {logging_mixin.py:115} INFO - [2022-06-22 17:01:36,355] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 17:01:36,356] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:01:36,371] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 17:02:06,459] {processor.py:153} INFO - Started process (PID=10668) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:02:06,459] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 17:02:06,459] {logging_mixin.py:115} INFO - [2022-06-22 17:02:06,459] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:02:06,463] {logging_mixin.py:115} INFO - [2022-06-22 17:02:06,462] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 17:02:06,463] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:02:06,476] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 17:02:36,563] {processor.py:153} INFO - Started process (PID=10698) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:02:36,564] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 17:02:36,564] {logging_mixin.py:115} INFO - [2022-06-22 17:02:36,564] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:02:36,567] {logging_mixin.py:115} INFO - [2022-06-22 17:02:36,567] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 10, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 17:02:36,567] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:02:36,580] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.019 seconds
[2022-06-22 17:03:05,655] {processor.py:153} INFO - Started process (PID=10728) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:03:05,657] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 17:03:05,657] {logging_mixin.py:115} INFO - [2022-06-22 17:03:05,657] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:03:05,661] {logging_mixin.py:115} INFO - [2022-06-22 17:03:05,661] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 9, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 17:03:05,661] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:03:05,674] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.021 seconds
[2022-06-22 17:03:35,760] {processor.py:153} INFO - Started process (PID=10760) to work on /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:03:35,761] {processor.py:641} INFO - Processing file /opt/airflow/dags/02_data_process_dag.py for tasks to queue
[2022-06-22 17:03:35,761] {logging_mixin.py:115} INFO - [2022-06-22 17:03:35,761] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:03:35,764] {logging_mixin.py:115} INFO - [2022-06-22 17:03:35,764] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/02_data_process_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/02_data_process_dag.py", line 9, in <module>
    from airflow.operators.python import TriggerDagRunOperator, TriggerRule
ImportError: cannot import name 'TriggerDagRunOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py)
[2022-06-22 17:03:35,764] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/02_data_process_dag.py
[2022-06-22 17:03:35,785] {processor.py:161} INFO - Processing /opt/airflow/dags/02_data_process_dag.py took 0.026 seconds
