[2022-06-28 15:00:51,441] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process-food-waste-data.trigger manual__2022-06-28T14:54:55.699826+00:00 [queued]>
[2022-06-28 15:00:51,449] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process-food-waste-data.trigger manual__2022-06-28T14:54:55.699826+00:00 [queued]>
[2022-06-28 15:00:51,449] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 15:00:51,449] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-28 15:00:51,449] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 15:00:51,462] {taskinstance.py:1377} INFO - Executing <Task(TriggerDagRunOperator): trigger> on 2022-06-28 14:54:55.699826+00:00
[2022-06-28 15:00:51,489] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-06-28 15:00:51,489] {standard_task_runner.py:52} INFO - Started process 387 to run task
[2022-06-28 15:00:51,491] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process-food-waste-data', 'trigger', 'manual__2022-06-28T14:54:55.699826+00:00', '--job-id', '517', '--raw', '--subdir', 'DAGS_FOLDER/02_data_process_dag.py', '--cfg-path', '/tmp/tmpi9pj5zkt', '--error-file', '/tmp/tmpies6r7_n']
[2022-06-28 15:00:51,492] {standard_task_runner.py:80} INFO - Job 517: Subtask trigger
[2022-06-28 15:00:51,527] {task_command.py:370} INFO - Running <TaskInstance: process-food-waste-data.trigger manual__2022-06-28T14:54:55.699826+00:00 [running]> on host ffbfbfe57984
[2022-06-28 15:00:51,579] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process-food-waste-data
AIRFLOW_CTX_TASK_ID=trigger
AIRFLOW_CTX_EXECUTION_DATE=2022-06-28T14:54:55.699826+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-28T14:54:55.699826+00:00
[2022-06-28 15:00:52,937] {trigger_dagrun.py:181} INFO - Waiting for data_to_dw_bq on 2022-06-28T15:00:51.580497+00:00 to become allowed state ['success'] ...
[2022-06-28 15:01:53,001] {trigger_dagrun.py:181} INFO - Waiting for data_to_dw_bq on 2022-06-28T15:00:51.580497+00:00 to become allowed state ['success'] ...
[2022-06-28 15:02:53,065] {trigger_dagrun.py:181} INFO - Waiting for data_to_dw_bq on 2022-06-28T15:00:51.580497+00:00 to become allowed state ['success'] ...
[2022-06-28 15:03:28,168] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-06-28 15:03:28,169] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 387. PIDs of all processes in the group: [387]
[2022-06-28 15:03:28,169] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 387
[2022-06-28 15:03:28,169] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-06-28 15:03:28,196] {process_utils.py:75} INFO - Process psutil.Process(pid=387, status='terminated', exitcode=0, started='15:00:51') (387) terminated with exit code 0
